name: "_Benchmark"

on:
  workflow_call:
    inputs:
      runs-on:
        default: "ubuntu-latest"
        required: false
        type: string

jobs:
  stress-ng:
    timeout-minutes: 1 # 60
    runs-on: ${{ inputs.runs-on }}
    steps:
      # - run: |
      #     sudo add-apt-repository ppa:colin-king/stress-ng
      #     sudo apt update
      #     sudo apt install stress-ng
      # - run: stress-ng --all 16

      - run: wget https://cdn.geekbench.com/Geekbench-6.0.0-Linux.tar.gz
      - run: tar -xvf Geekbench-6.0.0-Linux.tar.gz
      - run: cd Geekbench-6.0.0-Linux
      - run: ./geekbench6

      - run: sudo apt install sysbench
      - run: sysbench cpu --threads=2 run
      
      - run: sudo apt install p7zip-full
      - run: 7z b