name: "_Benchmark"

on:
  workflow_call:
    inputs:
      runs-on:
        default: "ubuntu-latest"
        required: false
        type: string

jobs:
  # geekbench:
  #   runs-on: ${{ inputs.runs-on }}
  #   steps:
  #     - run: wget https://cdn.geekbench.com/Geekbench-6.2.0-Linux.tar.gz
  #     - run: tar -xvf Geekbench-6.2.0-Linux.tar.gz
  #     - run: |
  #         res=$(sudo ./Geekbench-6.2.0-Linux/geekbench6 | grep 'view your results online:' -A 2)
  #         echo "::notice:: $res"
  sysbench:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: sudo apt install sysbench
      - run: sysbench cpu --threads=2 run