name: "Benchmark"

on:
  workflow_call:
    inputs:
      runs-on:
        default: "ubuntu-latest"
        required: false
        type: string

jobs:
  stress-ng:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: |
          sudo add-apt-repository ppa:colin-king/stress-ng
          sudo apt update
          sudo apt install stress-ng
      - run: stress-ng --all 16
  sysbench:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: sudo apt install sysbench
      - run: sysbench cpu --threads=2 run
  _7z:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: sudo apt install p7zip-full
      - run: 7z b
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: |
            await core.summary
            .addHeading('Test Results')
            .addCodeBlock(generateTestResults(), "js")
            .addTable([
              [{data: 'File', header: true}, {data: 'Result', header: true}],
              ['foo.js', 'Pass ✅'],
              ['bar.js', 'Fail ❌'],
              ['test.js', 'Pass ✅']
            ])
            .addLink('View staging deployment!', 'https://github.com')
            .write()