name: "_Benchmark"

on:
  workflow_call:
    inputs:
      runs-on:
        default: "ubuntu-latest"
        required: false
        type: string

jobs:
  stress-ng:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: wget https://cdn.geekbench.com/Geekbench-6.2.0-Linux.tar.gz
      - run: tar -xvf Geekbench-6.2.0-Linux.tar.gz
      - run: sudo ./Geekbench-6.2.0-Linux/geekbench6

      - run: sudo apt install sysbench
      - run: sysbench cpu --threads=2 run
      
      - run: sudo apt install p7zip-full
      - run: 7z b