name: "4. Delete Larger Runners"

on:
  workflow_dispatch:

env:
  ORG: ${{ github.event.repository.owner.login }}
  GITHUB_TOKEN: ${{ secrets.PAT }}
  RUNNER_GROUP_NAME: 'larger-runners'
  
jobs:
  get-runner-group:
    runs-on: ubuntu-latest
    outputs:
      runner_group_id: ${{ steps.get.outputs.runner_group_id }}
    steps:
      - id: get
        run: |
          runner_group_id="$(gh api '/orgs/${{ env.ORG }}/actions/runner-groups?per_page=100' | jq -r '.runner_groups[] | select(.name == "${{ env.RUNNER_GROUP_NAME }}") | .id')"
          echo "runner_group_id=${runner_group_id}" >> $GITHUB_OUTPUT
  get-runner-ids:
    runs-on: ubuntu-latest
    outputs:
      runner_ids: ${{ steps.get.outputs.runner_ids }}
    steps:
      - id: get
        run: |
          runner_ids="$(gh api '/orgs/octodemo/actions/larger-runners?per_page=100' --jq '[.runners.[] | select(.name=="4-core" or .name=="8-core" or .name=="16-core" or .name=="32-core" or .name=="64-core") | .id]')"
          echo "runner_ids=${runner_ids}" >> $GITHUB_OUTPUT
  delete-runners:
    runs-on: ubuntu-latest
    needs: get-runner-ids
    if: ${{ needs.get-runner-ids.outputs.runner_ids != '[]' && needs.get-runner-ids.outputs.runner_ids != '' }}
    strategy:
      matrix:
        image: [ 'ubuntu-latest' ]
        runner_ids: ${{ fromJSON(needs.get-runner-ids.outputs.runner_ids) }}
    steps:
      - run: gh api --method DELETE /orgs/${{ env.ORG }}/actions/larger-runners/${{ matrix.runner_ids }}
  delete-runner-group:
    runs-on: ubuntu-latest
    needs: [ delete-runners, get-runner-group ]
    # Run this even if the previous job is skipped
    if: always() && !contains(needs.*.result, 'failure')
    steps:
      - run: |
          for i in {1..8}; do
            gh api --method DELETE /orgs/${{ env.ORG }}/actions/runner-groups/${{ needs.get-runner-group.outputs.runner_group_id }} && break || true
            sleep 30
          done