name: "Generate Larger Runners"

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  create-runner-group:
    runs-on: ubuntu-latest
    steps:
      - run: gh api /orgs/octodemo/actions/runner-groups -f name="larger-runners" -f visibility="selected" -f selected_repository_ids="['${{ github.repository }}}}']"
  generate-runners:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ['ubuntu-latest', 'larger-4', 'larger-8', 'larger-16', 'larger-32', 'larger-64']
        image: ['ubuntu-latest']
        size: ['large', 'xlarge', '2xlarge', '4xlarge', '8xlarge']
        runner_group_id: ['']
    steps:
      - run: gh api /orgs/octodemo/actions/larger-runners -f name="${{ matrix.name }}" -f image="${{ matrix.image }}" -f size="${{ matrix.size }}" -F runner_group_id="${{ matrix.runner_group_id }}"