name: "Generate Larger Runners"

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  
jobs:
  create-runner-group:
    runs-on: ubuntu-latest
    outputs:
      runner_group_id: ${{ steps.create.outputs.runner_group_id }}
    steps:
      - run: gh --version
      - id: create
        run: |
          runner_group_id="$(gh api /orgs/octodemo/actions/runner-groups -f name="larger-runners" -f visibility="selected" -F selected_repository_ids[]=${{ github.event.repository.id }} | jq -r '.id')"
          echo "runner_group_id=$runner_group_id" >> "$GITHUB_OUTPUT"
  generate-runners:
    runs-on: ubuntu-latest
    needs: create-runner-group
    strategy:
      matrix:
        image: [ 'ubuntu-latest' ]
        size: ['large', 'xlarge', '2xlarge', '4xlarge', '8xlarge']
        runner_group_id: ['${{ needs.create-runner-group.outputs.runner_group_id }}']
    steps:
      - run: echo ${{ needs.create-runner-group.outputs.runner_group_id }}
      - run: gh api /orgs/octodemo/actions/larger-runners -f name="${{ matrix.size }}" -f image="${{ matrix.image }}" -f size="${{ matrix.size }}" -F runner_group_id=${{ matrix.runner_group_id }}