name: "Larger Runners Benchmark"

on:
  workflow_dispatch:

jobs:
  codeql:
    name: codeql
    strategy:
      matrix:
        runs-on: ['ubuntu-latest', '4-core', '8-core', '16-core', '32-core', '64-core']
    uses: ./.github/workflows/benchmark.yml
    with:
      runs-on: ${{ matrix.runs-on }}