name: "2. Larger Runners Benchmark"

on:
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        runs-on: ['ubuntu-latest', '4-core', '8-core', '16-core', '32-core', '64-core']
    uses: ./.github/workflows/benchmark.yml
    with:
      runs-on: ${{ matrix.runs-on }}
  evaluate-org-workflow-usage:
    # needs: benchmark
    uses: austenstone/github-toolkits/.github/workflows/evaluate-workflow-usage.yml@main
